name: location_protocol
description: A Dart library for building cryptographically verifiable, Location Protocol compliant records.
version: 0.1.0
homepage: https://github.com/DecentralizedGeo/location-protocol-dart
repository: https://github.com/DecentralizedGeo/location-protocol-dart
documentation: https://pub.dev/documentation/location_protocol/latest/
issue_tracker: https://github.com/DecentralizedGeo/location-protocol-dart/issues
topics:
  - location
  - protocol
  - ethereum
  - eas
  - geohash
  - h3
  - verification

environment:
  sdk: ^3.11.0

dependencies:
  on_chain: ^8.0.0
  blockchain_utils: ^6.0.0
  geobase: ^1.5.0

dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0
