// AUTO-GENERATED by scripts/docs_snippet_extractor.dart — DO NOT EDIT
// Regenerate with: dart run scripts/docs_snippet_extractor.dart

// ignore_for_file: avoid_print

@Tags(['doc-snippets'])
library;

import 'package:test/test.dart';
import 'package:location_protocol/location_protocol.dart';

import '../test_helpers/dotenv_loader.dart';

void main() {
  group('README', tags: ['sepolia'], () {
    final env = loadDotEnv();
    final sepoliaRpcUrl = env['SEPOLIA_RPC_URL'] ?? '';
    final sepoliaPrivateKey = env['SEPOLIA_PRIVATE_KEY'] ?? '';

    test('Quick Start (L94)', () async {
      if (sepoliaRpcUrl.isEmpty || sepoliaPrivateKey.isEmpty) {
        markTestSkipped('Missing SEPOLIA_RPC_URL or SEPOLIA_PRIVATE_KEY in .env');
        return;
      }

    final rpcUrl = sepoliaRpcUrl;
    final privateKey = sepoliaPrivateKey;

      try {
      
        // 1. Define a schema with business-specific fields.
        //    LP base fields (lp_version, srs, location_type, location) are prepended automatically.
        final schema = SchemaDefinition(fields: [
          SchemaField(type: 'uint256', name: 'observedAt'),
          SchemaField(type: 'string', name: 'memo'),
          SchemaField(type: 'address', name: 'observer'),
        ]);
      
        // Print the full EAS schema string (LP fields + your fields)
        print(schema.toEASSchemaString());
        // => string lp_version,string srs,string location_type,string location,uint256 observedAt,string memo,address observer
      
        // 2. Create an LP payload with a GeoJSON point location.
        final payload = LPPayload(
          lpVersion: '0.1.0',
          srs: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84',
          locationType: 'geojson-point',
          location: {'type': 'Point', 'coordinates': [-122.4194, 37.7749]},
        );
      
        // 3. Create an OffchainSigner targeting Sepolia.
        //    Replace with a real private key; never commit secrets.
        const privateKeyHex = 'ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'; // 64 hex chars, no 0x prefix
        final addresses = ChainConfig.forChainId(11155111)!; // Sepolia
      
        final signer = OffchainSigner.fromPrivateKey(
          privateKeyHex: privateKeyHex,
          chainId: 11155111,
          easContractAddress: addresses.eas,
        );
      
        // 4. Sign the attestation offchain (EIP-712 typed data, no RPC needed).
        final signed = await signer.signOffchainAttestation(
          schema: schema,
          lpPayload: payload,
          userData: {
            'observedAt': BigInt.from(DateTime.now().millisecondsSinceEpoch ~/ 1000),
            'memo': 'Rooftop sensor reading',
            'observer': signer.signerAddress,
          },
        );
      
        print('UID: ${signed.uid}');
        print('Signer: ${signed.signer}');
      
        // 5. Verify the signed attestation locally.
        final result = signer.verifyOffchainAttestation(signed);
        assert(result.isValid, 'Attestation verification failed: ${result.reason}');
        print('Valid: ${result.isValid}');
        print('Recovered address: ${result.recoveredAddress}');
      } catch (error) {
        final message = error.toString().toLowerCase();
        if (message.contains('already known')) {
          markTestSkipped('Skipping flaky Sepolia mempool duplicate transaction.');
          return;
        }
        rethrow;
      }
    });

  });

  group('how-to-add-custom-location-type', () {
    tearDown(() => LocationValidator.resetCustomTypes());

    group('Step sequence', () {
      test('Step 1 — Register a custom validator (L13)', () async {
        // Register a custom location type called 'plus-code'
        // A Google Plus Code looks like '8FW4V75V+8Q'
        LocationValidator.register('plus-code', (location) {
          if (location is! String) {
            throw ArgumentError('plus-code location must be a String, got ${location.runtimeType}');
          }
          // Plus codes: 8 chars + '+' + 2+ chars, base-20 charset
          final plusCodeRegex = RegExp(r'^[23456789CFGHJMPQRVWX]{8}\+[23456789CFGHJMPQRVWX]{2,}$');
          if (!plusCodeRegex.hasMatch(location.toUpperCase())) {
            throw ArgumentError('Invalid plus-code format: $location');
          }
        });
      });

      test('Step 2 — Use the custom type in an LP payload (L39)', () async {
        // Register a custom location type called 'plus-code'
        // A Google Plus Code looks like '8FW4V75V+8Q'
        LocationValidator.register('plus-code', (location) {
          if (location is! String) {
            throw ArgumentError('plus-code location must be a String, got ${location.runtimeType}');
          }
          // Plus codes: 8 chars + '+' + 2+ chars, base-20 charset
          final plusCodeRegex = RegExp(r'^[23456789CFGHJMPQRVWX]{8}\+[23456789CFGHJMPQRVWX]{2,}$');
          if (!plusCodeRegex.hasMatch(location.toUpperCase())) {
            throw ArgumentError('Invalid plus-code format: $location');
          }
        });

        final lpPayload = LPPayload(
          lpVersion: '1.0.0',
          srs: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84',
          locationType: 'plus-code',
          location: '8FW4V75V+8Q',
        );
        // Succeeds — custom validator is called and passes
      });

    });

    test('Constraints (L72)', () async {
      // In your test file:
      LocationValidator.resetCustomTypes();
    });

    test('Constraints (L57)', () {
      expect(() {
          LocationValidator.register('geojson-point', (location) {});
      }, throwsA(isA<ArgumentError>()));
    });


  });

  group('how-to-register-and-attest-onchain', tags: ['sepolia'], () {
    final env = loadDotEnv();
    final sepoliaRpcUrl = env['SEPOLIA_RPC_URL'] ?? '';
    final sepoliaPrivateKey = env['SEPOLIA_PRIVATE_KEY'] ?? '';

    group('Step sequence', () {
      test('Step 1 — Set up your RPC provider (L60)', () async {
        if (sepoliaRpcUrl.isEmpty || sepoliaPrivateKey.isEmpty) {
          markTestSkipped('Missing SEPOLIA_RPC_URL or SEPOLIA_PRIVATE_KEY in .env');
          return;
        }

        try {
            // Adapted from doc snippet: uses loadDotEnv() instead of Platform.environment.
            // Doc uses EAS_RPC_URL/EAS_PRIVATE_KEY; tests use SEPOLIA_RPC_URL/SEPOLIA_PRIVATE_KEY.
            const chainId = 11155111; // Sepolia

            final provider = DefaultRpcProvider(
              rpcUrl: sepoliaRpcUrl,
              privateKeyHex: sepoliaPrivateKey,
              chainId: chainId,
            );
        } catch (error) {
          final message = error.toString().toLowerCase();
          if (message.contains('already known')) {
            markTestSkipped('Skipping flaky Sepolia mempool duplicate transaction.');
            return;
          }
          rethrow;
        }
      });

      test('Step 2 — Register the schema (L87)', () async {
        if (sepoliaRpcUrl.isEmpty || sepoliaPrivateKey.isEmpty) {
          markTestSkipped('Missing SEPOLIA_RPC_URL or SEPOLIA_PRIVATE_KEY in .env');
          return;
        }

        try {
            // Adapted from doc snippet: uses loadDotEnv() instead of Platform.environment.
            // Doc uses EAS_RPC_URL/EAS_PRIVATE_KEY; tests use SEPOLIA_RPC_URL/SEPOLIA_PRIVATE_KEY.
            const chainId = 11155111; // Sepolia

            final provider = DefaultRpcProvider(
              rpcUrl: sepoliaRpcUrl,
              privateKeyHex: sepoliaPrivateKey,
              chainId: chainId,
            );

            // Prerequisites from tutorial (schema + LP payload)
            final schema = SchemaDefinition(
              fields: [
                SchemaField(type: 'uint256', name: 'timestamp'),
                SchemaField(type: 'string', name: 'memo'),
              ],
            );

            final lpPayload = LPPayload(
              lpVersion: '1.0.0',
              srs: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84',
              locationType: 'geojson-point',
              location: {'type': 'Point', 'coordinates': [-103.771556, 44.967243]},
            );

            final registryClient = SchemaRegistryClient(provider: provider);

            // Compute the UID locally before registering
            final expectedUID = SchemaRegistryClient.computeSchemaUID(schema);
            print('Expected schema UID: $expectedUID');

            // Register on-chain (or reuse an existing UID if already registered)
            final registerResult = await registryClient.register(schema);
            print('Schema registered: ${registerResult.uid}');
            print('Transaction: ${registerResult.txHash}');
        } catch (error) {
          final message = error.toString().toLowerCase();
          if (message.contains('already known')) {
            markTestSkipped('Skipping flaky Sepolia mempool duplicate transaction.');
            return;
          }
          rethrow;
        }
      });

      test('Step 3 — Attest onchain (L116)', () async {
        if (sepoliaRpcUrl.isEmpty || sepoliaPrivateKey.isEmpty) {
          markTestSkipped('Missing SEPOLIA_RPC_URL or SEPOLIA_PRIVATE_KEY in .env');
          return;
        }

        try {
            // Adapted from doc snippet: uses loadDotEnv() instead of Platform.environment.
            // Doc uses EAS_RPC_URL/EAS_PRIVATE_KEY; tests use SEPOLIA_RPC_URL/SEPOLIA_PRIVATE_KEY.
            const chainId = 11155111; // Sepolia

            final provider = DefaultRpcProvider(
              rpcUrl: sepoliaRpcUrl,
              privateKeyHex: sepoliaPrivateKey,
              chainId: chainId,
            );

            // Prerequisites from tutorial (schema + LP payload)
            final schema = SchemaDefinition(
              fields: [
                SchemaField(type: 'uint256', name: 'timestamp'),
                SchemaField(type: 'string', name: 'memo'),
              ],
            );

            final lpPayload = LPPayload(
              lpVersion: '1.0.0',
              srs: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84',
              locationType: 'geojson-point',
              location: {'type': 'Point', 'coordinates': [-103.771556, 44.967243]},
            );

            final registryClient = SchemaRegistryClient(provider: provider);

            // Compute the UID locally before registering
            final expectedUID = SchemaRegistryClient.computeSchemaUID(schema);
            print('Expected schema UID: $expectedUID');

            // Register on-chain (or reuse an existing UID if already registered)
            final registerResult = await registryClient.register(schema);
            print('Schema registered: ${registerResult.uid}');
            print('Transaction: ${registerResult.txHash}');

            final easClient = EASClient(provider: provider);

            final attestResult = await easClient.attest(
              schema: schema,
              lpPayload: lpPayload,
              userData: {
                'timestamp': BigInt.from(DateTime.now().millisecondsSinceEpoch ~/ 1000),
                'memo': 'Onchain field survey checkpoint',
              },
            );

            print('Attestation UID:   ${attestResult.uid}');
            print('Transaction hash:  ${attestResult.txHash}');
            print('Block number:      ${attestResult.blockNumber}');
        } catch (error) {
          final message = error.toString().toLowerCase();
          if (message.contains('already known')) {
            markTestSkipped('Skipping flaky Sepolia mempool duplicate transaction.');
            return;
          }
          rethrow;
        }
      });

      test('Step 4 — (Optional) Timestamp an offchain attestation (L143)', () async {
        if (sepoliaRpcUrl.isEmpty || sepoliaPrivateKey.isEmpty) {
          markTestSkipped('Missing SEPOLIA_RPC_URL or SEPOLIA_PRIVATE_KEY in .env');
          return;
        }

        try {
            // Adapted from doc snippet: uses loadDotEnv() instead of Platform.environment.
            // Doc uses EAS_RPC_URL/EAS_PRIVATE_KEY; tests use SEPOLIA_RPC_URL/SEPOLIA_PRIVATE_KEY.
            const chainId = 11155111; // Sepolia

            final provider = DefaultRpcProvider(
              rpcUrl: sepoliaRpcUrl,
              privateKeyHex: sepoliaPrivateKey,
              chainId: chainId,
            );

            // Prerequisites from tutorial (schema + LP payload)
            final schema = SchemaDefinition(
              fields: [
                SchemaField(type: 'uint256', name: 'timestamp'),
                SchemaField(type: 'string', name: 'memo'),
              ],
            );

            final lpPayload = LPPayload(
              lpVersion: '1.0.0',
              srs: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84',
              locationType: 'geojson-point',
              location: {'type': 'Point', 'coordinates': [-103.771556, 44.967243]},
            );

            // Offchain signing prerequisite for timestamp step
            const testPrivateKey = 'ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80';

            final easAddress = ChainConfig.forChainId(chainId)!.eas;

            final signer = OffchainSigner.fromPrivateKey(
              privateKeyHex: testPrivateKey,
              chainId: chainId,
              easContractAddress: easAddress,
            );

            final signed = await signer.signOffchainAttestation(
              schema: schema,
              lpPayload: lpPayload,
              userData: {
                'timestamp': BigInt.from(DateTime.now().millisecondsSinceEpoch ~/ 1000),
                'memo': 'Prerequisite for timestamp test',
              },
            );

            final registryClient = SchemaRegistryClient(provider: provider);

            // Compute the UID locally before registering
            final expectedUID = SchemaRegistryClient.computeSchemaUID(schema);
            print('Expected schema UID: $expectedUID');

            // Register on-chain (or reuse an existing UID if already registered)
            final registerResult = await registryClient.register(schema);
            print('Schema registered: ${registerResult.uid}');
            print('Transaction: ${registerResult.txHash}');

            final easClient = EASClient(provider: provider);

            final attestResult = await easClient.attest(
              schema: schema,
              lpPayload: lpPayload,
              userData: {
                'timestamp': BigInt.from(DateTime.now().millisecondsSinceEpoch ~/ 1000),
                'memo': 'Onchain field survey checkpoint',
              },
            );

            print('Attestation UID:   ${attestResult.uid}');
            print('Transaction hash:  ${attestResult.txHash}');
            print('Block number:      ${attestResult.blockNumber}');

            // Assumes `signed` is a SignedOffchainAttestation from OffchainSigner
            final timestampResult = await easClient.timestamp(signed.uid);

            print('Timestamped UID:  ${timestampResult.uid}');
            print('Block timestamp:  ${timestampResult.time}');
            print('Transaction hash: ${timestampResult.txHash}');
        } catch (error) {
          final message = error.toString().toLowerCase();
          if (message.contains('already known')) {
            markTestSkipped('Skipping flaky Sepolia mempool duplicate transaction.');
            return;
          }
          rethrow;
        }
      });

    });

  });

  group('how-to-wallet-onchain-attest', () {
    group('Step sequence', () {
      test('Step 1 — Build the ABI-encoded calldata (L20)', () async {

          final schema = SchemaDefinition(
            fields: [SchemaField(type: 'string', name: 'memo')],
          );

          final lpPayload = LPPayload(
            lpVersion: '1.0.0',
            srs: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84',
            locationType: 'geojson-point',
            location: {'type': 'Point', 'coordinates': [-73.9857, 40.7484]},
          );

          final callData = EASClient.buildAttestCallData(
            schema: schema,
            lpPayload: lpPayload,
            userData: {'memo': 'My attestation'},
          );

          print('callData length: ${callData.length}');
      });

      test('Step 2 — Build the wallet transaction request (L51)', () async {

          final schema = SchemaDefinition(
            fields: [SchemaField(type: 'string', name: 'memo')],
          );

          final lpPayload = LPPayload(
            lpVersion: '1.0.0',
            srs: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84',
            locationType: 'geojson-point',
            location: {'type': 'Point', 'coordinates': [-73.9857, 40.7484]},
          );

          final callData = EASClient.buildAttestCallData(
            schema: schema,
            lpPayload: lpPayload,
            userData: {'memo': 'My attestation'},
          );

          print('callData length: ${callData.length}');

          final chainId = 11155111; // Sepolia
          final easAddress = ChainConfig.forChainId(chainId)!.eas;
          const myWalletAddress = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266';

          final txRequest = TxUtils.buildTxRequest(
            to: easAddress,
            data: callData,
            from: myWalletAddress, // omit if your wallet SDK infers the sender
          );

          // txRequest is:
          // {
          //   'to':    '0xC2679fBD37d54388Ce493F1DB75320D236e1815e',
          //   'data':  '0x<abi-encoded calldata>',
          //   'value': '0x0',
          //   'from':  '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
          // }
          print('to:    ${txRequest['to']}');
          print('value: ${txRequest['value']}');
      });

      test('Step 3 — Submit via your wallet SDK (L79)', () async {

          final schema = SchemaDefinition(
            fields: [SchemaField(type: 'string', name: 'memo')],
          );

          final lpPayload = LPPayload(
            lpVersion: '1.0.0',
            srs: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84',
            locationType: 'geojson-point',
            location: {'type': 'Point', 'coordinates': [-73.9857, 40.7484]},
          );

          final callData = EASClient.buildAttestCallData(
            schema: schema,
            lpPayload: lpPayload,
            userData: {'memo': 'My attestation'},
          );

          print('callData length: ${callData.length}');

          final chainId = 11155111; // Sepolia
          final easAddress = ChainConfig.forChainId(chainId)!.eas;
          const myWalletAddress = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266';

          final txRequest = TxUtils.buildTxRequest(
            to: easAddress,
            data: callData,
            from: myWalletAddress, // omit if your wallet SDK infers the sender
          );

          // txRequest is:
          // {
          //   'to':    '0xC2679fBD37d54388Ce493F1DB75320D236e1815e',
          //   'data':  '0x<abi-encoded calldata>',
          //   'value': '0x0',
          //   'from':  '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
          // }
          print('to:    ${txRequest['to']}');
          print('value: ${txRequest['value']}');

          // Pass txRequest to your wallet SDK — exact API varies by SDK:
          // Privy:       final txHash = await privy.sendTransaction(txRequest);
          // FlutterWeb3: final txHash = await provider.request('eth_sendTransaction', [txRequest]);
          print('Transaction request ready: $txRequest');
      });

    });

  });

  group('reference-environment', tags: ['sepolia'], () {
    final env = loadDotEnv();
    final sepoliaRpcUrl = env['SEPOLIA_RPC_URL'] ?? '';
    final sepoliaPrivateKey = env['SEPOLIA_PRIVATE_KEY'] ?? '';

    test('Chain selection (L98)', () async {
      if (sepoliaRpcUrl.isEmpty || sepoliaPrivateKey.isEmpty) {
        markTestSkipped('Missing SEPOLIA_RPC_URL or SEPOLIA_PRIVATE_KEY in .env');
        return;
      }

    final rpcUrl = sepoliaRpcUrl;
    final privateKey = sepoliaPrivateKey;

      try {
      final provider = DefaultRpcProvider(
        rpcUrl: rpcUrl,
        privateKeyHex: privateKey,
        chainId: 11155111, // Sepolia
      );
      } catch (error) {
        final message = error.toString().toLowerCase();
        if (message.contains('already known')) {
          markTestSkipped('Skipping flaky Sepolia mempool duplicate transaction.');
          return;
        }
        rethrow;
      }
    });

  });

  group('tutorial-first-attestation', () {
    group('Step sequence', () {
      test('Step 1 — Define your schema (L46)', () async {
        
          // Define your business schema
          // LP base fields (lp_version, srs, location_type, location) are auto-prepended
          final schema = SchemaDefinition(
            fields: [
              SchemaField(type: 'uint256', name: 'timestamp'),
              SchemaField(type: 'string', name: 'memo'),
            ],
          );
        
          print(schema.toEASSchemaString());
          // => "string lp_version,string srs,string location_type,string location,uint256 timestamp,string memo"
      });

      test('Step 2 — Create an LP payload (L80)', () async {
        
          // Define your business schema
          // LP base fields (lp_version, srs, location_type, location) are auto-prepended
          final schema = SchemaDefinition(
            fields: [
              SchemaField(type: 'uint256', name: 'timestamp'),
              SchemaField(type: 'string', name: 'memo'),
            ],
          );
        
          print(schema.toEASSchemaString());
          // => "string lp_version,string srs,string location_type,string location,uint256 timestamp,string memo"

          // Create the LP payload — validates all 4 base fields on construction
          final lpPayload = LPPayload(
            lpVersion: '1.0.0',
            srs: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84',           // OGC CRS URI
            locationType: 'geojson-point',
            location: {'type': 'Point', 'coordinates': [-103.771556, 44.967243]},
          );
        
          print('Location type: ${lpPayload.locationType}');
          print('Location: ${lpPayload.location}');
          // If LPPayload construction succeeds, all 4 fields are valid.
      });

      test('Step 3 — Sign the attestation offchain (L109)', () async {
        
          // Define your business schema
          // LP base fields (lp_version, srs, location_type, location) are auto-prepended
          final schema = SchemaDefinition(
            fields: [
              SchemaField(type: 'uint256', name: 'timestamp'),
              SchemaField(type: 'string', name: 'memo'),
            ],
          );
        
          print(schema.toEASSchemaString());
          // => "string lp_version,string srs,string location_type,string location,uint256 timestamp,string memo"

          // Create the LP payload — validates all 4 base fields on construction
          final lpPayload = LPPayload(
            lpVersion: '1.0.0',
            srs: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84',           // OGC CRS URI
            locationType: 'geojson-point',
            location: {'type': 'Point', 'coordinates': [-103.771556, 44.967243]},
          );
        
          print('Location type: ${lpPayload.locationType}');
          print('Location: ${lpPayload.location}');
          // If LPPayload construction succeeds, all 4 fields are valid.

          // A test private key — NEVER use a real key in source code
          const testPrivateKey = '1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef';
          const chainId = 11155111; // Sepolia
        
          final easAddress = ChainConfig.forChainId(chainId)!.eas;
        
          final signer = OffchainSigner.fromPrivateKey(
            privateKeyHex: testPrivateKey,
            chainId: chainId,
            easContractAddress: easAddress,
          );
        
          final signed = await signer.signOffchainAttestation(
            schema: schema,
            lpPayload: lpPayload,
            userData: {
              'timestamp': BigInt.from(DateTime.now().millisecondsSinceEpoch ~/ 1000),
              'memo': 'Tutorial checkpoint',
            },
          );
        
          print('Attestation UID: ${signed.uid}');
          print('Signer:          ${signed.signer}');
      });

      test('Step 4 — Verify the attestation (L150)', () async {
        
          // Define your business schema
          // LP base fields (lp_version, srs, location_type, location) are auto-prepended
          final schema = SchemaDefinition(
            fields: [
              SchemaField(type: 'uint256', name: 'timestamp'),
              SchemaField(type: 'string', name: 'memo'),
            ],
          );
        
          print(schema.toEASSchemaString());
          // => "string lp_version,string srs,string location_type,string location,uint256 timestamp,string memo"

          // Create the LP payload — validates all 4 base fields on construction
          final lpPayload = LPPayload(
            lpVersion: '1.0.0',
            srs: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84',           // OGC CRS URI
            locationType: 'geojson-point',
            location: {'type': 'Point', 'coordinates': [-103.771556, 44.967243]},
          );
        
          print('Location type: ${lpPayload.locationType}');
          print('Location: ${lpPayload.location}');
          // If LPPayload construction succeeds, all 4 fields are valid.

          // A test private key — NEVER use a real key in source code
          const testPrivateKey = '1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef';
          const chainId = 11155111; // Sepolia
        
          final easAddress = ChainConfig.forChainId(chainId)!.eas;
        
          final signer = OffchainSigner.fromPrivateKey(
            privateKeyHex: testPrivateKey,
            chainId: chainId,
            easContractAddress: easAddress,
          );
        
          final signed = await signer.signOffchainAttestation(
            schema: schema,
            lpPayload: lpPayload,
            userData: {
              'timestamp': BigInt.from(DateTime.now().millisecondsSinceEpoch ~/ 1000),
              'memo': 'Tutorial checkpoint',
            },
          );
        
          print('Attestation UID: ${signed.uid}');
          print('Signer:          ${signed.signer}');

          final result = signer.verifyOffchainAttestation(signed);
        
          print('Valid:            ${result.isValid}');
          print('Recovered signer: ${result.recoveredAddress}');
        
          // The recovered address should match the signer's address
          assert(result.isValid, 'Signature verification failed');
          assert(
            result.recoveredAddress.toLowerCase() == signer.signerAddress.toLowerCase(),
            'Recovered address mismatch',
          );
      });

      test('Step 5 — Inspect the signed attestation (L177)', () async {
        
          // Define your business schema
          // LP base fields (lp_version, srs, location_type, location) are auto-prepended
          final schema = SchemaDefinition(
            fields: [
              SchemaField(type: 'uint256', name: 'timestamp'),
              SchemaField(type: 'string', name: 'memo'),
            ],
          );
        
          print(schema.toEASSchemaString());
          // => "string lp_version,string srs,string location_type,string location,uint256 timestamp,string memo"

          // Create the LP payload — validates all 4 base fields on construction
          final lpPayload = LPPayload(
            lpVersion: '1.0.0',
            srs: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84',           // OGC CRS URI
            locationType: 'geojson-point',
            location: {'type': 'Point', 'coordinates': [-103.771556, 44.967243]},
          );
        
          print('Location type: ${lpPayload.locationType}');
          print('Location: ${lpPayload.location}');
          // If LPPayload construction succeeds, all 4 fields are valid.

          // A test private key — NEVER use a real key in source code
          const testPrivateKey = '1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef';
          const chainId = 11155111; // Sepolia
        
          final easAddress = ChainConfig.forChainId(chainId)!.eas;
        
          final signer = OffchainSigner.fromPrivateKey(
            privateKeyHex: testPrivateKey,
            chainId: chainId,
            easContractAddress: easAddress,
          );
        
          final signed = await signer.signOffchainAttestation(
            schema: schema,
            lpPayload: lpPayload,
            userData: {
              'timestamp': BigInt.from(DateTime.now().millisecondsSinceEpoch ~/ 1000),
              'memo': 'Tutorial checkpoint',
            },
          );
        
          print('Attestation UID: ${signed.uid}');
          print('Signer:          ${signed.signer}');

          final result = signer.verifyOffchainAttestation(signed);
        
          print('Valid:            ${result.isValid}');
          print('Recovered signer: ${result.recoveredAddress}');
        
          // The recovered address should match the signer's address
          assert(result.isValid, 'Signature verification failed');
          assert(
            result.recoveredAddress.toLowerCase() == signer.signerAddress.toLowerCase(),
            'Recovered address mismatch',
          );

          // Inspect the full signed attestation
          print('Schema UID: ${signed.schemaUID}');
          print('Version:    ${signed.version}');
          print('Revocable:  ${signed.revocable}');
          print('r: ${signed.signature.r}');
          print('s: ${signed.signature.s}');
          print('v: ${signed.signature.v}');
      });

    });

    test('Complete program listing (L204)', () async {
      
        // Step 1 — Define your schema
        // LP base fields (lp_version, srs, location_type, location) are auto-prepended
        final schema = SchemaDefinition(
          fields: [
            SchemaField(type: 'uint256', name: 'timestamp'),
            SchemaField(type: 'string', name: 'memo'),
          ],
        );
      
        print(schema.toEASSchemaString());
        // => "string lp_version,string srs,string location_type,string location,uint256 timestamp,string memo"
      
        // Step 2 — Create the LP payload
        final lpPayload = LPPayload(
          lpVersion: '1.0.0',
          srs: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84',
          locationType: 'geojson-point',
          location: {'type': 'Point', 'coordinates': [-103.771556, 44.967243]},
        );
      
        print('Location type: ${lpPayload.locationType}');
        print('Location: ${lpPayload.location}');
      
        // Step 3 — Sign the attestation offchain
        // A test private key — NEVER use a real key in source code
        const testPrivateKey = '1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef';
        const chainId = 11155111; // Sepolia
      
        final easAddress = ChainConfig.forChainId(chainId)!.eas;
      
        final signer = OffchainSigner.fromPrivateKey(
          privateKeyHex: testPrivateKey,
          chainId: chainId,
          easContractAddress: easAddress,
        );
      
        final signed = await signer.signOffchainAttestation(
          schema: schema,
          lpPayload: lpPayload,
          userData: {
            'timestamp': BigInt.from(DateTime.now().millisecondsSinceEpoch ~/ 1000),
            'memo': 'Tutorial checkpoint',
          },
        );
      
        print('Attestation UID: ${signed.uid}');
        print('Signer:          ${signed.signer}');
      
        // Step 4 — Verify the attestation
        final result = signer.verifyOffchainAttestation(signed);
      
        print('Valid:            ${result.isValid}');
        print('Recovered signer: ${result.recoveredAddress}');
      
        assert(result.isValid, 'Signature verification failed');
        assert(
          result.recoveredAddress.toLowerCase() == signer.signerAddress.toLowerCase(),
          'Recovered address mismatch',
        );
      
        // Step 5 — Inspect the signed attestation
        print('Schema UID: ${signed.schemaUID}');
        print('Version:    ${signed.version}');
        print('Revocable:  ${signed.revocable}');
        print('r: ${signed.signature.r}');
        print('s: ${signed.signature.s}');
        print('v: ${signed.signature.v}');
    });

  });

  group('tutorial-wallet-signer', () {
    group('Step sequence', () {
      test('Step 2 — Wire the signer into `OffchainSigner` (L91)', () async {
        // Replace with your wallet-backed Signer implementation:
          const privateKeyHex =
              'ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80';

          final walletSigner = LocalKeySigner(privateKeyHex: privateKeyHex);

          final chainId = 11155111; // Sepolia
          final easAddress = ChainConfig.forChainId(chainId)!.eas;

          final offchainSigner = OffchainSigner(
            signer: walletSigner,
            chainId: chainId,
            easContractAddress: easAddress,
          );

          print('Signer address: ${offchainSigner.signerAddress}');
          // => Signer address: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      });

      test('Step 3 — Sign and verify an attestation (L119)', () async {
        // Replace with your wallet-backed Signer implementation:
          const privateKeyHex =
              'ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80';

          final walletSigner = LocalKeySigner(privateKeyHex: privateKeyHex);

          final chainId = 11155111; // Sepolia
          final easAddress = ChainConfig.forChainId(chainId)!.eas;

          final offchainSigner = OffchainSigner(
            signer: walletSigner,
            chainId: chainId,
            easContractAddress: easAddress,
          );

          print('Signer address: ${offchainSigner.signerAddress}');
          // => Signer address: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266

          final schema = SchemaDefinition(
            fields: [SchemaField(type: 'string', name: 'memo')],
          );

          final lpPayload = LPPayload(
            lpVersion: '1.0.0',
            srs: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84',
            locationType: 'geojson-point',
            location: {'type': 'Point', 'coordinates': [-73.9857, 40.7484]},
          );

          final signed = await offchainSigner.signOffchainAttestation(
            schema: schema,
            lpPayload: lpPayload,
            userData: {'memo': 'Signed via wallet adapter'},
          );

          print('UID:    ${signed.uid}');
          print('Signer: ${signed.signer}');

          final result = offchainSigner.verifyOffchainAttestation(signed);
          print('Valid:  ${result.isValid}');
          // => Valid:  true
      });

    });

    test('Complete program listing (L153)', () async {

        const privateKeyHex =
            'ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80';

        // In production: replace with your wallet-backed Signer implementation.
        final walletSigner = LocalKeySigner(privateKeyHex: privateKeyHex);
        final chainId = 11155111;
        final easAddress = ChainConfig.forChainId(chainId)!.eas;

        final offchainSigner = OffchainSigner(
          signer: walletSigner,
          chainId: chainId,
          easContractAddress: easAddress,
        );

        final schema = SchemaDefinition(
          fields: [SchemaField(type: 'string', name: 'memo')],
        );

        final lpPayload = LPPayload(
          lpVersion: '1.0.0',
          srs: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84',
          locationType: 'geojson-point',
          location: {'type': 'Point', 'coordinates': [-73.9857, 40.7484]},
        );

        final signed = await offchainSigner.signOffchainAttestation(
          schema: schema,
          lpPayload: lpPayload,
          userData: {'memo': 'Signed via wallet adapter'},
        );

        print('UID:    ${signed.uid}');
        print('Signer: ${signed.signer}');

        final result = offchainSigner.verifyOffchainAttestation(signed);
        print('Valid:  ${result.isValid}');
    });

  });

}
